analyzer:
  plugins:
    - ../custom_lint

custom_lint:
  rules:
    - avoid_returning_widgets:
      exclude:
        - class_name: ExcludeWidget 
          method_name: excludeWidgetMethod
        - method_name: excludeMethod
