include: package:solid_lints/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - cyclomatic_complexity_metric:
      max_complexity: 4
    - number_of_parameters:
      max_parameters: 2
